<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>CentreSoutien.Desktop</RootNamespace>
    <AssemblyName>CentreSoutien</AssemblyName>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>false</SelfContained>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CentreSoutien.Infrastructure\CentreSoutien.Infrastructure.csproj" />
    <ProjectReference Include="..\CentreSoutien.Presentation\CentreSoutien.Presentation.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\logo.png" />
    <Resource Include="Assets\app.ico" />
    <Resource Include="Assets\Fonts\*.ttf" />
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Assets\Fonts\OFL-*.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>Licenses\%(Filename)%(Extension)</Link>
    </None>
  </ItemGroup>
</Project>
